theme: minima
title: DataCleaner Review
author: Sarah Rutherford
description: This is a blog post as part of an assignment for CMU course 11695. It discusses the tool DataCleaner and its capabilities in terms of MLOps.
